# Generated by Django 4.1 on 2024-03-07 11:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('movie', models.FileField(null=True, upload_to='upload_video/')),
                ('info', models.TextField(blank=True, max_length=1000, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('fish_mixed', models.CharField(blank=True, max_length=200, null=True)),
                ('temp', models.IntegerField(blank=True, null=True)),
                ('fish_size', models.IntegerField(blank=True, null=True)),
                ('aquarium_size', models.IntegerField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('food', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_file_name', models.ImageField(upload_to='icon_img/')),
                ('icon_name', models.CharField(max_length=50)),
                ('icon_text', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mail', models.EmailField(db_index=True, max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('icon', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='net_a_db.icon')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='user/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_a_db.fishinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_a_db.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FishPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_file_name', models.ImageField(upload_to='upload_img/')),
                ('display_number', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('fish_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_a_db.fishinfo')),
            ],
        ),
        migrations.AddField(
            model_name='fishinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='net_a_db.userinfo'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_a_db.fishinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_a_db.userinfo')),
            ],
        ),
    ]
