# Generated by Django 4.1 on 2024-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0002_alter_fishphoto_fish_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinfo',
            name='movie',
            field=models.FileField(blank=True, null=True, upload_to='upload_video/'),
        ),
    ]
