# Generated by Django 4.1 on 2024-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0003_alter_fishinfo_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishinfo',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
