# Generated by Django 4.1 on 2024-03-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0007_alter_fishinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinfo',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='upload_img/'),
        ),
    ]
