# Generated by Django 4.1 on 2024-03-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0008_alter_fishinfo_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinfo',
            name='category',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
