# Generated by Django 4.1 on 2024-03-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0011_fishinfo_good'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'fish')},
        ),
    ]
