# Generated by Django 4.1 on 2024-03-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0015_alter_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinfo',
            name='aquarium_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fishinfo',
            name='temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
